### ISSUE TITLE
Include `job` filter for node resource checks

### ISSUE THREAD

**Issue by dave08** [vfarcic/docker-flow-monitor#24]
If we have multiple node exporter services limited say to only workers or managers, the @node_[...] checks should be limited to that node exporter service's job like this:
```
(sum(node_memory_MemTotal{job="monitor-exporters_node-exporter-sm"}) BY (instance) - sum(node_memory_MemFree{job="monitor-exporters_node-exporter-sm"} + node_memory_Buffers{job="monitor-exporters_node-exporter-sm"} + node_memory_Cached{job="monitor-exporters_node-exporter-sm"}) BY (instance)) / sum(node_memory_MemTotal{job="monitor-exporters_node-exporter-sm"}) BY (instance)
```

**Comment by vfarcic** [comment]
@dave08 Can you please let me know the shortcut behind this expression? The closest I could find is `@node_mem_limit`. However, it is not the same. It expands to:

```
(sum by (instance) (node_memory_MemTotal) - sum by (instance) (node_memory_MemFree + node_memory_Buffers + node_memory_Cached)) / sum by (instance) (node_memory_MemTotal) > [SOME_VALUE]
```

Is that the one you're using?

**Comment by dave08** [comment]
Yes, I just gave an example of how I think it might look after the change, am I right? Also, this could apply to all yhe node related shortcuts like fs.. I just haven't (luckily) reached 80% disk usage yet...

**Comment by vfarcic** [comment]
The reason I asked for the shortcut is because none expands to the expression you used. You're probably using the older Prometheus 1.x based DFM.

Anyways, most of the shortcuts had `job` baked in, except two. Now that's corrected and all are having `job` (or an equivalent). You can see the current list of shortcuts through https://github.com/vfarcic/docker-flow-monitor/blob/master/server/server.go#L261.

A new tag `vfarcic/docker-flow-monitor:17.12.29-41` is building while I'm typing this. It'll be available in a few minutes.
