### ISSUE TITLE
How do flexible labels work?

### ISSUE THREAD

**Issue by dave08** [vfarcic/docker-flow-monitor#40]
@thomasjpfan What do `com.df.env=prod` and `com.df.metricType=system` do? Are they just informational labels and can be replaced by whatever is needed, or are they required? If so, what does each do? Also, where can one retreive this info in Prometheus queries and alerts, is there an additional metric, is it added to all metrics sent from the exporter?

Also, I'm trying to decide if this can replace basi/node-exporter image that sends the host name in a `host` metric.. this allows me to combine other metrics to it and get the node's host name instead of node exporter's ip, can flexible labels replace this function (and maybe give this possibility even in cadvisor metrics)?

**Comment by thomasjpfan** [comment]
1. In the tutorial, I used them just as an example of labels. The are used in combination with environmental variable `DF_SCRAPE_TARGET_LABELS` in `monitor`:

```yaml
  monitor:
    image: vfarcic/docker-flow-monitor
    environment:
      - DF_SCRAPE_TARGET_LABELS=env,metricType
```

This tells prometheus to translate `com.df.env` and `com.df.metricType` into labels for specific targets. By default the labels `node`, and `service` are included.

2. It's added to all metrics from the exporter. For example, if you want to know the total memory usage of services from a docker stack on node `swarm-1`:
```
sum(container_memory_usage_bytes{container_label_com_docker_stack_namespace!="", node="swarm-1"})
```

3. Since the `node` label is the hostname and included in every metric, I can see how this replace the functionality of `basi/node-exporter`.

**Comment by vfarcic** [comment]
Can we close this issue?
