### ISSUE TITLE
Idea for scaling a service without Jenkins

### ISSUE THREAD

**Issue by thomasjpfan** [vfarcic/docker-flow-monitor#5]
While reviewing the source code for https://github.com/alexellis/faas, I saw they created a custom webhook: https://github.com/alexellis/faas/blob/master/gateway/handlers/alerthandler.go to scale a docker service. They have an alertmanager configured to signal the webhook when the service needs to be scaled up: https://github.com/alexellis/faas/blob/master/prometheus/alertmanager.yml.

Incorporating the custom webhook as a microservice to scale services would eliminate the need to use Jenkins to perform scaling.

**Comment by vfarcic** [comment]
My plan is to build a service that would do the scaling and connect it to AM in a similar way as the one you described. The only problem is time. There's never enough of it. So, I started with Jenkins since it allows a fast and easy way to script everything. Once I have all the use-cases clear (e.g. scaling services, scaling nodes, and so on) I'd start converting Jenkins pipelines to a service. Would you like to help? If we would work on it together, I could change the plan and start working on it soon.

**Comment by thomasjpfan** [comment]
I'll set up a separate repo as a proof of concept that scales services using your url scheme `http://scaler?service=go-demo_main&scale=1'`. I'm in the process of incorporating vendoring through https://github.com/golang/dep and a CI system through travis.

**Comment by vfarcic** [comment]
That sounds great! Please post a link to the repo.

**Comment by thomasjpfan** [comment]
The repo is at https://github.com/thomasjpfan/docker-scaler.

I changed the url scheme a little. To scale up a service, the POST request would go to `http://scaler?service=go-demo_main&delta=1`. Similarly to scale down a service: `http://scaler?service=go-demo_main&delta=-1`.

**Comment by vfarcic** [comment]
I went through the code and it looks great. I'll try it out during the weekend or Monday and get back to you with any comments I might have. A few notes until then...

Would you like to publish it in http://dockerflow.com? We can create a new subdomain like scaler.dockerflow.com and host the docs on the cluster I have for the projects. If that sounds OK, I'd need mkdocs files.

Would it be OK if I add it to the DevOps 2.2 Toolkit?

I was planning to do some scripts for scaling AWS nodes and, later on, the same with other providers. I think it might be interesting to add it to that project instead. What do you think?

**Comment by thomasjpfan** [comment]
1. I'll put in the mkdocs files for the subdomain.
2. I'm okay with it being added to DevOps 2.2 Toolkit.
3. AWS scaling seems good. I think it should to be careful with scaling **down** manager nodes, maybe even restrict scaling to just worker nodes and scaling **up** manager nodes.

**Comment by carl-utter** [comment]
@thomasjpfan 

> AWS scaling seems good. I think it should to be careful with scaling down manager nodes, maybe even restrict scaling to just worker nodes and scaling up manager nodes.

Thank you very much for your DevOps 2.2 Toolkit contribution... your concept is definitely a good and valued one. We have a multi-cluster Production Swarm(s) running on AWS EC2 instances and our Platform was developed using Viktor's DevOps 2.1 Toolkit as a primer. As such, we are consuming/implementing everything we can that comes out of Viktor's DevOps 2.2 Toolkit, which is how I came about this thread.

I agree with the "should to be careful with scaling down manager nodes" part but I must humbly disagree with the "restrict scaling to just worker nodes and scaling up manager nodes" portion...

Allow me to explain:
Currently we are averaging a running cost of $4300 per month for the EC2 instances used by our Swarm Clusters and we have to do everything we can to mitigate unnecessary costs, so we consider this to be the 2nd reason why the ability to scale up or down per load demand is important).

We provision our Clusters over 3 AZs in our AWS Region and we always want have at least 1 Manager Node in each AZ to meet our HA requirements, so, we should always have a minimum of 3 manager nodes. A concern that we have to contend with though is that for various reasons we limit certain services to only Manager Nodes (such as DF Proxy, Vault, OAuth) since they have been tailored to utilize information that can only be fetched on a Manager Node.

As such, this is why I feel it should be imperative that both "Manager" and "Worker" nodes can be scalable "in both directions" so that we can continue to only pay AWS for what we need and only when we need it while meeting our Platform's Load demands.

It seems to me that having the same scaling thresholds (min/max-replicas as applied to services) would be a fine addition as a control for cluster nodes (of type). Perhaps there is a way to apply such configurable scaling thresholds in your concept?

@vfarcic - Thank you good sir for all your help and effort... we are entering our 20th week of uptime!

**Comment by thomasjpfan** [comment]
Defining thresholds for both manager and worker nodes would be the most flexible solution. I will accommodate these configuration options into my concept.

**Comment by vfarcic** [comment]
I'm sorry I could not go through your latest changes. This week is busier than usual. I'll do my best to go through it early next week.

**Comment by vfarcic** [comment]
Closing the issue with a reference to the [thomasjpfan/docker-scaler](https://github.com/thomasjpfan/docker-scaler).
